services:
  mongo:
    image: mongo:latest  
    container_name: mongo-1
    ports:
      - "27017:27017"  
    # une variable d’environnement pour initialiser une base de données par défaut
    environment: 
      - MONGO_INITDB_DATABASE=gestion_taches_cc3  
    volumes:
      - mongo_data:/data/db  
  auth-service:
  # Indique que l’image sera construite à partir du répertoire ./auth-service en utilisant le Dockerfile
    build:
      context: ./auth-service  
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "5000:5000"  
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - JWT_SECRET=9a92ad437a5c3e8b63889d7423ba7271f8c1445c3f44595eab7908b303c2a6410335bec9940e6a997e71b157bdc23a46ccad04f08d1b27316dd829b6323a093d  
      - PORT=5000
    depends_on:
      - mongo  

  projet-service:
    build:
      context: ./projet-service  
      dockerfile: Dockerfile
    container_name: projet-service

    ports:
      - "5001:5001"  
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - JWT_SECRET=9a92ad437a5c3e8b63889d7423ba7271f8c1445c3f44595eab7908b303c2a6410335bec9940e6a997e71b157bdc23a46ccad04f08d1b27316dd829b6323a093d  
      - PORT=5001
    depends_on:
      - mongo  
      - auth-service

  tache-service:
    build:
      context: ./tache-service 
      dockerfile: Dockerfile
    container_name: tache-service 
    ports:
      - "5002:5002"  
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - JWT_SECRET=9a92ad437a5c3e8b63889d7423ba7271f8c1445c3f44595eab7908b303c2a6410335bec9940e6a997e71b157bdc23a46ccad04f08d1b27316dd829b6323a093d 
      - PORT=5002
    depends_on:
      - mongo 
      - auth-service 
      - projet-service
  chat-service:
    build:
      context: ./chat-service 
      dockerfile: Dockerfile
    container_name: chat-service 
    ports:
      - "5005:5005"  
    environment:
      - MONGODB_URL=mongodb://mongo:27017/gestion_taches_cc3
      - JWT_SECRET=9a92ad437a5c3e8b63889d7423ba7271f8c1445c3f44595eab7908b303c2a6410335bec9940e6a997e71b157bdc23a46ccad04f08d1b27316dd829b6323a093d 
      - PORT=5005
    depends_on:
      - mongo 
      - auth-service 
      - projet-service

volumes:
  mongo_data:
